const products=[
    {
        _id:'1',
        name:'Airpods',
        image:'/images/airpods.jpg',
        description:
            'loremjkdhsjkkasbf bfdhbcdsabcbsaxcbxa',
        brand:'Apple',
        category:'Electronics',
        price:7862,
        countInStock:10,
        rating:4.5,
        numReviews:12,

    },
    {
        _id: '2',
        name: 'Gaming Mouse',
        image: '/images/alexa.jpg',
        description: 'Ergonomic design with customizable buttons and RGB lighting.',
        brand: 'Logitech',
        category: 'Accessories',
        price: 3450,
        countInStock: 20,
        rating: 4.7,
        numReviews: 34,
    },
    {
        _id: '3',
        name: 'Mechanical Keyboard',
        image: '/images/camera.jpg',
        description: 'High-performance mechanical keyboard with programmable keys.',
        brand: 'Razer',
        category: 'Accessories',
        price: 6999,
        countInStock: 15,
        rating: 4.8,
        numReviews: 45,
    },
    {
        _id: '4',
        name: 'Gaming Headset',
        image: '/images/mouse.jpg',
        description: 'Surround sound gaming headset with noise-canceling microphone.',
        brand: 'SteelSeries',
        category: 'Accessories',
        price: 5499,
        countInStock: 25,
        rating: 4.6,
        numReviews: 28,
    },
    {
        _id: '5',
        name: '4K Gaming Monitor',
        image: '/images/phone.jpg',
        description: 'Ultra HD 4K monitor with high refresh rate and low response time.',
        brand: 'ASUS',
        category: 'Electronics',
        price: 25999,
        countInStock: 0,
        rating: 4.9,
        numReviews: 15,
    },
    {
        _id: '6',
        name: 'VR Headset',
        image: '/images/playstation.jpg',
        description: 'Immersive virtual reality headset with high-resolution display.',
        brand: 'Oculus',
        category: 'Electronics',
        price: 34999,
        countInStock: 5,
        rating: 1,
        numReviews: 18,
    }
    
]
export default products